- name: Install java
  become: true
  apt:
    name: openjdk-11-jdk
    state: present

- name: Import jenkins key from url
  become: true
  apt_key:
    state: present
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key

- name: Download Long Term Jenkins release
  become: true
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install jenkins
  become: true
  apt:
    name: jenkins
    state: latest

- name: Update Jenkins
  become: true
  apt:
    name: jenkins
    update_cache: true

- name: Add Docker For Jenkins
  become: true
  shell: sudo usermod -aG docker jenkins

- name: Set ownership and permissions for the directory
  become: yes
  become_user: root
  file:
    path: /home/ubuntu
    owner: jenkins
    group: jenkins
    mode: "0755"
  tags: set_permissions

- name: Add ubuntu user to jenkins group
  become: yes
  become_user: root
  user:
    name: ubuntu
    groups: jenkins
    append: yes
  tags: add_user_to_group

- name: Add jenkins user to Ubuntu group
  become: yes
  become_user: root
  user:
    name: jenkins
    groups: ubuntu
    append: yes
  tags: add_user_to_group

  notify: Restart Jenkins Service

- name: Start Jenkins service
  become: true
  service:
    name: jenkins
    state: started

- name: Retrieve Jenkins admin password
  command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
  register: admin_password
  changed_when: false

- name: Manually complete Jenkins setup
  debug:
    msg: |
      Please access Jenkins through the web browser and complete the initial setup.
      URL: http://{{ hostvars['Project_Server']['ansible_host'] }}:8080
      Admin API Token: {{ admin_password.stdout }}
