- name: Setup AWS, Docker, Kubernetes and Jenkins
  hosts: Project_Server
  become: true
  vars:
    kubectl_version: "v1.27.4"
  vars_files:
    - vars.yml
  roles:
    - Install_Dependencies
    - Install_Aws
    - Install_Kubectl
    - Install_Docker
    - Install_Jenkins
