apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  # Add other ConfigMap data here if needed

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_password: eW91cl9yb290X3Bhc3N3b3Jk
