apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: configmap-secret-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-secret-rolebinding
  namespace: default
subjects:
  - kind: User
    name: system:node:ip-10-0-1-124.ec2.internal  # Replace with the actual node name
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: configmap-secret-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  DATABASE_HOST: mysql-service
  MYSQL_USER: root

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: eW91cl9yb290X3Bhc3N3b3Jk
  MYSQL_PASSWORD: eW91cl9yb290X3Bhc3N3b3Jk
  MYSQL_DATABASE: QnVja2V0TGlzdA==
