apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  DATABASE_HOST: mysql-service
  DATABASE_PORT: "3306"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_password: eW91cl9yb290X3Bhc3N3b3Jk
  database_name: QnVja2V0TGlzdA==
