apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  DATABASE_HOST: mysql-service
  DATABASE_PORT: "3306"
  MYSQL_USER: root

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: eW91cl9yb290X3Bhc3N3b3Jk
  MYSQL_PASSWORD: eW91cl9yb290X3Bhc3N3b3Jk
  MYSQL_DATABASE: QnVja2V0TGlzdA==
