apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: 812428914503.dkr.ecr.us-east-1.amazonaws.com/flask-app-repo:<ECR_IMAGE_TAG> # Replace <ECR_IMAGE_TAG> with the actual image tag
          ports:
            - containerPort: 5000
          env:
            - name: ECR_IMAGE_TAG
              value: <ECR_IMAGE_TAG> # Add this line to define the ECR_IMAGE_TAG environment variable
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
