apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: <ECR_REPO_IMAGE> # Replace <<ECR_REPO_IMAGE>> with the actual repo with tage name
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          env:
            - name: ECR_IMAGE_TAG
              value: <ECR_REPO_IMAGE> # Add this line to define the ECR_REPO_IMAGE environment variable
            - name: ECR_IMAGE_TAG
              value: <ECR_IMAGE_TAG> # Add this line to define the ECR_IMAGE_TAG environment variable
            - name: DB_HOST
              value: python-service
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database_name
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root_password
