apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: ingress-reader
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-ingress-reader
  namespace: default
subjects:
- kind: ServiceAccount
  name: jenkins  # Replace with the Jenkins service account name if different
  namespace: default
roleRef:
  kind: Role
  name: ingress-reader
  apiGroup: rbac.authorization.k8s.io
