apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-app-db-statefulset
spec:
  serviceName: "flask-app-db-service"  # The service name for the MySQL database
  replicas: 1  # Change the number of replicas as needed
  selector:
    matchLabels:
      app: flask-app-db
  template:
    metadata:
      labels:
        app: flask-app-db
    spec:
      containers:
      - name: flask-app-db
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root_password
          - name: MYSQL_DATABASE
            value: BucketList
          - name: MYSQL_ROOT_HOST
            value: '%'
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi  # Change the storage size as needed
