apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv  # Give it a unique name
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-03a9f2671085b891c  # Use the volume ID directly
    fsType: ext4
