apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-flask-app-db-statefulset-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
