kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-new-pvc
  labels:
    name: my-new-pvc

spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
