apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1a
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  hostPath:
     path: /var/lib/mysql
