apiVersion: batch/v1
kind: Job
metadata:
  name: sql-import-job
spec:
  template:
    metadata:
      name: mysql-statefulset
      labels:
        app: sql-import
    spec:
      containers:
        - name: mysql-client
          image: mysql:latest
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          command:
            - "sh"
            - "-c"
            - >
              mysql -h mysql-service -u root -pyour_root_password BucketList
              < /workspace/MySQL-and-Python/MySQL_Queries/BucketList.sql
      restartPolicy: Never
      volumes:
        - name: workspace-volume
          hostPath:
            path: /var/lib/jenkins/workspace/MyProject
