apiVersion: batch/v1
kind: Job
metadata:
  name: sql-import-job
spec:
  template:
    metadata:
      name: mysql-statefulset
      labels:
        app: sql-import
    spec:
      containers:
        - name: mysql-client
          image: mysql:latest
          command:
            - "sh"
            - "-c"
            - >
              mysql -h mysql-service -u root -pyour_root_password BucketList
              < MySQL-and-Python/MySQL_Queries/BucketList.sql
      restartPolicy: Never
