apiVersion: batch/v1
kind: Job
metadata:
  name: sql-import-job
spec:
  template:
    spec:
      containers:
        - name: mysql-client
          image: mysql:latest
          command:
            - "sh"
            - "-c"
            - >
              mysql -h mysql-service -u root -pyour_root_password BucketList
              < /var/lib/jenkins/workspace/MyProject/MySQL-and-Python/MySQL_Queries/BucketList.sql
      restartPolicy: Never
