apiVersion: batch/v1
kind: Job
metadata:
  name: sql-import-job
spec:
  template:
    spec:
      containers:
        - name: mysql-client
          image: mysql:latest
          volumeMounts:
            - name: sql-config-volume
              mountPath: /sql-scripts
      restartPolicy: Never
      volumes:
        - name: sql-config-volume
          configMap:
            name: mysql-configmap
