- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    executable: /bin/bash
  async: 300
  poll: 0

- name: Change permissions for Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: "0644"

- name: Add Docker repository to sources.list
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    create: yes

- name: Update package manager cache
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Install Docker Compose
  shell: curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
  args:
    executable: /bin/bash

- name: Add the user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Change permissions for the Docker socket
  file:
    path: /var/run/docker.sock
    mode: "0666"

  notify: Restart Docker Service
